### ISSUE TITLE
Debug Hold Request ID 1265

### ISSUE THREAD

**Issue by kfriedman** [NYPL/nypl-hold-request-consumer#20]
Hi,

So... it looks like we had some unexpected behavior for hold request ID 1265.

Apparently, this consumer was unable to retrieve the item for this hold request, posted a failure to `HoldRequestResult`, but still posted to ReCAP. This caused further processing downstream which ultimately resulted in another message (a `success` message) being posted to `HoldRequestResult`. This caused conflicts.

Can you investigate?

cc: @gkallenberg @emu47 @holingpoon

**Comment by kfriedman** [comment]
I think 1263 had the same issue. Could it be that you're posting a failure to `HoldRequestResult` on retryable errors?

**Comment by rhernand3z** [comment]
Fixed by #21 - Closing.
