### ISSUE TITLE
Multiple results posted / investigate SCSB Request logic?

### ISSUE THREAD

**Issue by kfriedman** [NYPL/nypl-hold-request-consumer#29]
We had a bunch of requests yesterday that had **two** results (failure and success) posted to the HoldRequestResult stream:

id | jobId | success | message
-- | -- | -- | --
785 | 217759b0589be3ce0 | false | {"message":"unable to retrieve Patron data from Patron Service for hold request record (785)","type":"hold-request-record-missing-patron-data"}
785 | 217759b0589be3ce0 | true |  
786 | 217859b058bfe2a50 | false | {"message":"unable to retrieve Patron data from Patron Service for hold request record (786)","type":"hold-request-record-missing-patron-data"}
786 | 217859b058bfe2a50 | true |  
787 | 217959b05cbb02ac2 | false | {"message":"unable to retrieve Patron data from Patron Service for hold request record (787)","type":"hold-request-record-missing-patron-data"}
787 | 217959b05cbb02ac2 | true |  
788 | 218159b061af288ae | false | {"message":"unable to retrieve Patron data from Patron Service for hold request record (788)","type":"hold-request-record-missing-patron-data"}
788 | 218159b061af288ae | true |  

This should never happen. I suspect it's because these requests originated from the SCSB UI but processing of the event failed retrieving Patron information. It looks like we might need to investigate/think through the logic and ensure that the first thing checked, before any dependent API calls that may fail, is whether it's a SCSB Request or not.

**Comment by rhernand3z** [comment]
Fixed by #30. Closing.
