### ISSUE TITLE
POST failed Hold Request records to HoldRequestResult Stream

### ISSUE THREAD

**Issue by rhernand3z** [NYPL/nypl-hold-request-consumer#9]
Using the NYPL StreamsClient, post failed HQ to the proper stream.

**Comment by rhernand3z** [comment]
@holingpoon -- can you provide the name of the stream?

Using the Node NYPL Streams Client -- https://github.com/NYPL-discovery/node-nypl-streams-client

stream name is required.

CC: @kfriedman

**Comment by holingpoon** [comment]
On the sandbox, the full name of the stream is
`arn:aws:kinesis:us-east-1:224280085904:stream/HoldRequestProcessed`

Confirming with @kfriedman

**Comment by rhernand3z** [comment]
I am assuming it will be 'HoldRequestProcessed' instead of the long ARN... seems like that is what the StreamsClient expects...

I thought the name was HoldRequestResult, good to get clarification.

CC: @holingpoon

**Comment by rhernand3z** [comment]
This issue is solved by #10
